name: MuslimMessages
main: xyz.xapktech.intervalMessages.IntervalMessagesPlugin
version: 1.0
api-version: 1.8
author: [Friedegg796]
description: Sends a random Islamic reminder from the config.yml file every 30 or so seconds.